version: '3.1'
services:
  db:
    image: postgres:latest
    container_name: mon-postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: products
      POSTGRES_PASSWORD: admin
    volumes:
      - ./.tmp/postgres:/var/lib/postgres
      - ./.tmp/postgres/scripts:/docker-entrypoint-initdb.d